In [1]:
import numpy as np 
import pandas as pd 

Mydata = pd.read_csv('../DataOut/bus_trip_all_points.csv')
AyyasData=pd.read_csv('../DataOut/processed_data/bus_running_times_feature_added_all.csv')
Aayyas_dwelltime_df=pd.read_csv('../DataOut/processed_data/bus_stop_times_feature_added_all.csv')

In [2]:
# get my data trip id == 4890
Mydata[Mydata['trip_id']==6542.0]

,id,deviceid,devicetime,latitude,longitude,speed,date,time,geometry,bus_stop,trip_id,direction
1289511,560231777,274,2021-10-01 06:58:03,7.298953,80.734112,11.87910,2021-10-01,06:58:03,POINT (195626.5749087095 232968.86523213168),BT02,6542.0,2
1289512,560335052,274,2021-10-01 07:51:36,7.291723,80.635137,4.85961,2021-10-01,07:51:36,POINT (184698.15187659665 232171.46420291165),BT01,6542.0,2

In [3]:
# # Convert the date column to datetime if it's not already in datetime format
# AyyasData['date'] = pd.to_datetime(AyyasData['date'])

# # Now you can filter based on both deviceid and date
# filtered_data = AyyasData[(AyyasData['deviceid'] == 274) & (AyyasData['date'] == pd.to_datetime('2021-10-01'))]
# filtered_data

In [4]:
# drop raws where only trip_id is null
AyyasData.dropna(subset=['trip_id'], inplace=True)

In [5]:
# show all the columns in pandas dataframes
pd.set_option('display.max_columns', None)

In [6]:
AyyasData.head()

,trip_id,deviceid,direction,segment,date,start_time,end_time,run_time,run_time_in_seconds,length,day_of_week,time_of_day,Sunday/holiday,saturday,weekday/end,week_no,rt(w-1),rt(w-2),rt(w-3),rt(t-1),rt(t-2),rt(n-1),rt(n-2),rt(n-3),hour_of_day,day,month,temp,precip,windspeed,conditions,dt(n-1)
0,1.0,262.0,1.0,1.0,2021-10-01,06:39:49,06:40:58,0 days 00:01:09,69.0,0.6261,4.0,6.50,0.0,0,1,1.0,96.0,96.0,96.0,96.0,96.0,96.0,96.0,96.0,6.0,1.0,10.0,20.0,0.0,6.1,Partially cloudy,0.0
1,1.0,262.0,1.0,2.0,2021-10-01,06:42:12,06:45:42,0 days 00:03:30,210.0,1.2808,4.0,6.50,0.0,0,1,1.0,247.0,247.0,247.0,247.0,247.0,69.0,247.0,247.0,6.0,1.0,10.0,20.0,0.0,6.1,Partially cloudy,74.0
2,1.0,262.0,1.0,3.0,2021-10-01,06:45:42,06:53:58,0 days 00:08:16,496.0,2.1125,4.0,6.75,0.0,0,1,1.0,506.0,506.0,506.0,506.0,506.0,210.0,69.0,506.0,6.0,1.0,10.0,20.0,0.0,6.1,Partially cloudy,0.0
3,1.0,262.0,1.0,4.0,2021-10-01,06:54:04,06:57:19,0 days 00:03:15,195.0,1.5513,4.0,6.75,0.0,0,1,1.0,192.0,192.0,192.0,192.0,192.0,496.0,210.0,69.0,6.0,1.0,10.0,20.0,0.0,6.1,Partially cloudy,6.0
4,1.0,262.0,1.0,5.0,2021-10-01,06:57:19,06:58:56,0 days 00:01:37,97.0,0.8450,4.0,6.75,0.0,0,1,1.0,114.0,114.0,114.0,114.0,114.0,195.0,496.0,210.0,6.0,1.0,10.0,20.0,0.0,6.1,Partially cloudy,0.0

In [7]:
# AyyasDataonly keep 'trip_id', 'deviceid', 'direction', 'date', 'start_time', 'end_time' columns
AyyasData_forComp = AyyasData[['trip_id', 'deviceid',  'date', 'start_time', 'end_time']]
# Convert 'start_time' and 'end_time' columns to datetime format ( start tieme and end time only have time in hh:mm:ss format)
# AyyasData_forComp['start_time'] = pd.to_datetime(AyyasData_forComp['start_time'], format='%H:%M:%S').dt.time
# AyyasData_forComp['end_time'] = pd.to_datetime(AyyasData_forComp['end_time'], format='%H:%M:%S').dt.time

# Convert 'start_time' and 'end_time' columns to datetime
AyyasData_forComp['start_time'] = pd.to_datetime(AyyasData_forComp['date'] + ' ' + AyyasData_forComp['start_time'])
AyyasData_forComp['end_time'] = pd.to_datetime(AyyasData_forComp['date'] + ' ' + AyyasData_forComp['end_time'])
# convert 'date' column to datetime format
AyyasData_forComp['date'] = pd.to_datetime(AyyasData_forComp['date'], format='%Y-%m-%d').dt.date

C:\Users\gw\AppData\Local\Temp\ipykernel_45456\1607620677.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  AyyasData_forComp['start_time'] = pd.to_datetime(AyyasData_forComp['date'] + ' ' + AyyasData_forComp['start_time'])
C:\Users\gw\AppData\Local\Temp\ipykernel_45456\1607620677.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  AyyasData_forComp['end_time'] = pd.to_datetime(AyyasData_forComp['date'] + ' ' + AyyasData_forComp['end_time'])
C:\Users\gw\AppData\Local\Temp\ipykernel_45456\1607620677.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  AyyasData_forComp['date'] = pd.to_datetime(AyyasData_forComp['date'], format='%Y-%m-%d').dt.date

In [8]:
# get a list of all columns in the dataframe
colls=list(AyyasData_forComp.columns)
print(colls)

['trip_id', 'deviceid', 'date', 'start_time', 'end_time']

In [9]:
# # group AyyasData_forComp by trip id, and pick any available value to each column , also create new two column of trip start time and trip end time, trip start time will be the earliest time of each trip on start_time column and the trip end time will be the last time value on end_time column in each trip id
# # these are the column names in the dataset ['trip_id', 'deviceid', 'date', 'start_time', 'end_time']
# AyyasData_forComp=AyyasData_forComp.groupby(['trip_id']).agg({'deviceid':'first','date':'first','start_time':'min','end_time':'max'}).reset_index()

In [10]:


# Group by 'trip_id' and aggregate
AyyasData_forComp = AyyasData_forComp.groupby(['trip_id']).agg(
    deviceid=pd.NamedAgg(column='deviceid', aggfunc='first'),
    date=pd.NamedAgg(column='date', aggfunc='first'),
    start_time=pd.NamedAgg(column='start_time', aggfunc='min'),
    end_time=pd.NamedAgg(column='end_time', aggfunc='max')
).reset_index()

# Resulting DataFrame
print(AyyasData_forComp)

       trip_id  deviceid        date          start_time            end_time
0          1.0     262.0  2021-10-01 2021-10-01 06:39:49 2021-10-01 07:27:32
1          3.0     274.0  2021-10-01 2021-10-01 06:58:03 2021-10-01 07:51:21
2          4.0     123.0  2021-10-01 2021-10-01 07:37:40 2021-10-01 08:15:44
3          8.0     274.0  2021-10-01 2021-10-01 08:40:27 2021-10-01 09:34:49
4          9.0     262.0  2021-10-01 2021-10-01 08:40:37 2021-10-01 09:33:22
...        ...       ...         ...                 ...                 ...
14123  25366.0    1358.0  2022-11-01 2022-11-01 17:00:34 2022-11-01 17:46:45
14124  25367.0    1377.0  2022-11-01 2022-11-01 17:40:45 2022-11-01 18:33:10
14125  25368.0     284.0  2022-11-01 2022-11-01 17:51:04 2022-11-01 18:35:06
14126  25369.0     513.0  2022-11-01 2022-11-01 18:08:04 2022-11-01 18:52:05
14127  25370.0     121.0  2022-11-01 2022-11-01 18:20:26 2022-11-01 19:02:30

[14128 rows x 5 columns]

In [11]:
AyyasData[AyyasData['trip_id']==3  ]

,trip_id,deviceid,direction,segment,date,start_time,end_time,run_time,run_time_in_seconds,length,day_of_week,time_of_day,Sunday/holiday,saturday,weekday/end,week_no,rt(w-1),rt(w-2),rt(w-3),rt(t-1),rt(t-2),rt(n-1),rt(n-2),rt(n-3),hour_of_day,day,month,temp,precip,windspeed,conditions,dt(n-1)
74040,3.0,274.0,2.0,21.0,2021-10-01,06:58:03,07:03:16,0 days 00:05:13,313.0,1.9418,4.0,6.75,0.0,0,1,1.0,354.0,354.0,354.0,354.0,354.0,354.0,354.0,354.0,6.0,1.0,10.0,20.0,0.0,6.1,Partially cloudy,0.0
74041,3.0,274.0,2.0,22.0,2021-10-01,07:04:00,07:06:03,0 days 00:02:03,123.0,0.9166,4.0,7.00,0.0,0,1,1.0,116.0,116.0,116.0,116.0,116.0,313.0,116.0,116.0,7.0,1.0,10.0,20.7,0.0,6.8,Partially cloudy,44.0
74042,3.0,274.0,2.0,23.0,2021-10-01,07:08:34,07:12:28,0 days 00:03:54,234.0,1.1479,4.0,7.00,0.0,0,1,1.0,175.0,175.0,175.0,175.0,175.0,123.0,313.0,175.0,7.0,1.0,10.0,20.7,0.0,6.8,Partially cloudy,151.0
74043,3.0,274.0,2.0,24.0,2021-10-01,07:13:41,07:17:16,0 days 00:03:35,215.0,1.3115,4.0,7.00,0.0,0,1,1.0,171.0,171.0,171.0,171.0,171.0,234.0,123.0,313.0,7.0,1.0,10.0,20.7,0.0,6.8,Partially cloudy,73.0
74044,3.0,274.0,2.0,25.0,2021-10-01,07:17:16,07:20:37,0 days 00:03:21,201.0,1.2594,4.0,7.25,0.0,0,1,1.0,222.0,222.0,222.0,222.0,222.0,215.0,234.0,123.0,7.0,1.0,10.0,20.7,0.0,6.8,Partially cloudy,0.0
74045,3.0,274.0,2.0,26.0,2021-10-01,07:21:59,07:24:39,0 days 00:02:40,160.0,1.0360,4.0,7.25,0.0,0,1,1.0,130.0,130.0,130.0,130.0,130.0,201.0,215.0,234.0,7.0,1.0,10.0,20.7,0.0,6.8,Partially cloudy,82.0
74046,3.0,274.0,2.0,27.0,2021-10-01,07:26:00,07:26:55,0 days 00:00:55,55.0,0.3844,4.0,7.25,0.0,0,1,1.0,39.0,39.0,39.0,39.0,39.0,160.0,201.0,215.0,7.0,1.0,10.0,20.7,0.0,6.8,Partially cloudy,81.0
74047,3.0,274.0,2.0,28.0,2021-10-01,07:27:50,07:30:37,0 days 00:02:47,167.0,0.8673,4.0,7.25,0.0,0,1,1.0,117.0,117.0,117.0,117.0,117.0,55.0,160.0,201.0,7.0,1.0,10.0,20.7,0.0,6.8,Partially cloudy,55.0
74048,3.0,274.0,2.0,29.0,2021-10-01,07:31:06,07:34:35,0 days 00:03:29,209.0,1.3970,4.0,7.50,0.0,0,1,1.0,189.0,189.0,189.0,189.0,189.0,167.0,55.0,160.0,7.0,1.0,10.0,20.7,0.0,6.8,Partially cloudy,29.0
74049,3.0,274.0,2.0,30.0,2021-10-01,07:35:26,07:40:44,0 days 00:05:18,318.0,2.5612,4.0,7.50,0.0,0,1,1.0,382.0,382.0,382.0,382.0,382.0,209.0,167.0,55.0,7.0,1.0,10.0,20.7,0.0,6.8,Partially cloudy,51.0
74050,3.0,274.0,2.0,31.0,2021-10-01,07:41:04,07:41:54,0 days 00:00:50,50.0,0.4169,4.0,7.50,0.0,0,1,1.0,59.0,59.0,59.0,59.0,59.0,318.0,209.0,167.0,7.0,1.0,10.0,20.7,0.0,6.8,Partially cloudy,20.0
74051,3.0,274.0,2.0,32.0,2021-10-01,07:42:14,07:46:06,0 days 00:03:52,232.0,1.2960,4.0,7.50,0.0,0,1,1.0,233.0,233.0,233.0,233.0,233.0,50.0,318.0,209.0,7.0,1.0,10.0,20.7,0.0,6.8,Partially cloudy,20.0
74052,3.0,274.0,2.0,33.0,2021-10-01,07:46:13,07:50:10,0 days 00:03:57,237.0,1.2245,4.0,7.75,0.0,0,1,1.0,253.0,253.0,253.0,253.0,253.0,232.0,50.0,318.0,7.0,1.0,10.0,20.7,0.0,6.8,Partially cloudy,7.0
74053,3.0,274.0,2.0,34.0,2021-10-01,07:50:21,07:51:21,0 days 00:01:00,60.0,0.6617,4.0,7.75,0.0,0,1,1.0,100.0,100.0,100.0,100.0,100.0,237.0,232.0,50.0,7.0,1.0,10.0,20.7,0.0,6.8,Partially cloudy,11.0

In [ ]:
AyyasData_forComp

In [ ]:
# get a list of all columns in the dataframe
colls=list(Mydata.columns)
print(colls)

In [ ]:
Mydata.head()

In [ ]:
Mydata_forComp=Mydata[['trip_id', 'deviceid', 'date', 'time']]
# Convert 'start_time' and 'end_time' columns to datetime format ( start tieme and end time only have time in hh:mm:ss format)
Mydata_forComp['time'] = pd.to_datetime(Mydata['date'] + ' ' + Mydata['time'])
# convert 'date' column to datetime format
Mydata_forComp['date'] = pd.to_datetime(Mydata['date'], format='%Y-%m-%d').dt.date

In [ ]:
# group Mydata by trip id and pick the middle value of every column , columns are ['trip_id', 'deviceid', 'date', 'time']

# Sort the data by 'trip_id' and 'time'
Mydata_forComp = Mydata_forComp.sort_values(by=['trip_id', 'time'])

# Calculate the number of rows in each 'trip_id' group
group_sizes = Mydata_forComp.groupby('trip_id').size().reset_index(name='group_size')

# Select the middle row from each 'trip_id' group
Mydata_forComp = Mydata_forComp.merge(group_sizes, on='trip_id')
Mydata_forComp['middle_row'] = Mydata_forComp['group_size'] // 2

# Select the middle values for each 'trip_id' group
Mydata_forComp = Mydata_forComp[Mydata_forComp.groupby('trip_id').cumcount() == Mydata_forComp['middle_row']]

# Cleanup: Drop the helper columns
Mydata_forComp.drop(columns=['group_size', 'middle_row'], inplace=True)

# Reset the index
Mydata_forComp.reset_index(drop=True, inplace=True)

# Resulting DataFrame with one middle time value for each 'trip_id' group
Mydata_forComp.head()

In [ ]:
AyyasData_forComp.head()

In [ ]:
Mydata_forComp.head()

In [ ]:
# make AyyasData_forComp deviceid integer without the decimal point
AyyasData_forComp['deviceid'] = AyyasData_forComp['deviceid'].astype(int)

In [ ]:
# Convert the date column to datetime if it's not already in datetime format
Mydata_forComp['date'] = pd.to_datetime(Mydata_forComp['date'])

# Now you can filter based on both deviceid and date
filtered_data = Mydata_forComp[(Mydata_forComp['deviceid'] == 274) & (Mydata_forComp['date'] == pd.to_datetime('2021-10-01'))]
filtered_data

In [ ]:
smaller_df, larger_df = AyyasData_forComp, Mydata_forComp

# Create a mapping dictionary based on common bus IDs, date, and time
mapping_dict = {}
i = 0
for index, row in smaller_df.iterrows():
    matching_rows = larger_df[
        (larger_df['deviceid'] == row['deviceid']) &
        (larger_df['time'] >= row['start_time']) &
        (larger_df['time'] <= row['end_time'])
    ]
    print (matching_rows, "-------------------------------")
    if len(matching_rows) >= 1:
        mapping_dict[row['trip_id']] = matching_rows.iloc[0]['trip_id']
    if i==2:
        break
    i += 1
# Update trip IDs in the smaller data frame using the mapping dictionary
smaller_df['trip_id'] = smaller_df['trip_id'].map(mapping_dict)

# Now, the trip IDs in the smaller data frame have been updated to match the larger data frame
print(smaller_df)

In [ ]:
Aayyas_dwelltime_df

In [ ]:
Aayyas_dwelltime_df['trip_id'] = Aayyas_dwelltime_df['trip_id'].map(mapping_dict)

In [ ]:
Aayyas_dwelltime_df

In [ ]:
# Count the number of unique key-value pairs in mapping_dict
unique_pairs = len({(key, value) for key, value in mapping_dict.items()})

print("Number of unique key-value pairs in mapping_dict:", unique_pairs)

In [ ]:
mapping_dict

In [ ]:
smaller_df

In [ ]:
# drop null rows Mydata
smaller_df.dropna(inplace=True)

In [ ]:
smaller_df

In [ ]:
# get the number of nan values in each column
Aayyas_dwelltime_df.isnull().sum()

In [ ]:
# get the number of nan values in each column
AyyasData.isnull().sum()

In [ ]:
AyyasData

In [ ]:
AyyasData['trip_id'] = AyyasData['trip_id'].map(mapping_dict)

In [ ]:
AyyasData

In [ ]:
# get the number of nan values in each column
AyyasData.isnull().sum()

In [ ]:
# drop raws where only trip_id is null
AyyasData.dropna(subset=['trip_id'], inplace=True)

Aayyas_dwelltime_df.dropna(subset=['trip_id'], inplace=True)

In [ ]:
Aayyas_dwelltime_df

In [ ]:
AyyasData

In [ ]:
# print number of unique trip_id in Mydata
print(Mydata['trip_id'].nunique())

In [ ]:
# get a list of values in mapping_dict dictionary
available_trip_ids=list(mapping_dict.values())

In [ ]:
available_trip_ids=list(set(available_trip_ids))

In [ ]:
len(available_trip_ids)

In [ ]:
# drop the rows in Mydata where trip_id is not in available_trip_ids
Mydata=Mydata[Mydata['trip_id'].isin(available_trip_ids)]

In [ ]:
Mydata

In [ ]:
# get my data trip id == 4890
AyyasData[AyyasData['trip_id']==2370]

In [ ]:
# save my data to csv file bus_trip_all_points_moddedDF.csv
Mydata.to_csv('../DataOut/bus_trip_all_points_moddedDF.csv', index=False)

# save AyyasData to csv file bus_running_times_feature_added_all_moddedDF.csv
AyyasData.to_csv('../DataOut/bus_running_times_feature_added_all_moddedDF.csv', index=False)

# save AyyasData to csv file bus_running_times_feature_added_all_moddedDF.csv
Aayyas_dwelltime_df.to_csv('../DataOut/bus_stop_times_feature_added_all_moddedDF.csv', index=False)