In [1]:
import numpy as np
import pandas as pd

runtime_pred=pd.read_csv('../DataOut/runtime_with_predictions.csv')
dwelltime_pred=pd.read_csv('../DataOut/dwelltime_with_predictions.csv')
bustop_locations=pd.read_csv('../Data Sets/bus_stops_and_terminals_654.csv')

In [2]:
# remove the pandas columnn limit
pd.set_option('display.max_columns', None)

In [3]:
runtime_pred

,trip_id,deviceid,direction,segment,run_time_in_seconds,length,day_of_week,time_of_day,Sunday/holiday,saturday,weekday/end,week_no,rt(w-1),rt(w-2),rt(w-3),rt(t-1),rt(t-2),rt(n-1),rt(n-2),rt(n-3),hour_of_day,day,month,temp,precip,windspeed,dt(n-1),year,conditions_encoded,start_float,dayparts,speed,acceleration,radial_acceleration,throttle_count,break_count,predicted_run_time
0,1511.0,117.0,1.0,1.0,75.0,0.63,0.0,6.50,0.0,0,1,39.0,130.0,100.0,113.0,113.0,113.0,113.0,113.0,113.0,6.0,10,10,19.7,0.000,4.0,0.0,2022,4.0,6.510556,0,6.344489,-0.322849,0.351416,1.000000,1.000000,111.11015
1,1511.0,117.0,1.0,2.0,321.0,1.28,0.0,6.50,0.0,0,1,39.0,270.0,207.0,279.0,279.0,279.0,75.0,279.0,279.0,6.0,10,10,19.7,0.000,4.0,42.0,2022,4.0,6.543056,0,8.279345,-0.010563,0.634614,1.000000,1.000000,252.84645
2,1511.0,117.0,1.0,3.0,523.0,2.11,0.0,6.50,0.0,0,1,39.0,537.0,480.0,445.0,487.0,487.0,321.0,75.0,487.0,6.0,10,10,19.7,0.000,4.0,15.0,2022,4.0,6.636389,0,7.863126,-0.089699,0.510328,7.000000,8.000000,529.71970
3,1511.0,117.0,1.0,4.0,211.0,1.55,0.0,6.75,0.0,0,1,39.0,201.0,197.0,209.0,209.0,209.0,523.0,321.0,75.0,6.0,10,10,19.7,0.000,4.0,68.0,2022,4.0,6.800556,0,9.098285,0.066004,0.322768,5.000000,6.000000,205.24037
4,1511.0,117.0,1.0,5.0,123.0,0.84,0.0,6.75,0.0,0,1,39.0,108.0,100.0,130.0,130.0,130.0,211.0,523.0,321.0,6.0,10,10,19.7,0.000,4.0,0.0,2022,4.0,6.859167,0,15.658757,-0.237839,0.335279,1.000000,0.000000,126.76441
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3515,3461.0,123.0,1.0,11.0,183.0,1.10,0.0,17.50,0.0,0,1,42.0,172.0,166.0,156.0,242.0,116.0,194.0,39.0,94.0,17.0,31,10,25.3,0.269,0.1,0.0,2022,1.0,17.676667,1,10.854414,-0.385668,0.460299,2.616114,3.113744,148.89400
3516,3461.0,123.0,1.0,12.0,173.0,1.31,0.0,17.50,0.0,0,1,42.0,183.0,170.0,172.0,142.0,150.0,183.0,194.0,39.0,17.0,31,10,25.3,0.269,0.1,10.0,2022,1.0,17.730278,1,11.492473,-0.314227,0.647867,3.112710,3.541966,150.72600
3517,3461.0,123.0,1.0,13.0,142.0,1.15,0.0,17.75,0.0,0,1,42.0,149.0,149.0,161.0,149.0,134.0,173.0,183.0,194.0,17.0,31,10,25.3,0.269,0.1,2.0,2022,1.0,17.778889,1,11.459195,-0.575089,0.667765,2.520482,2.867470,137.92944
3518,3461.0,123.0,1.0,14.0,121.0,0.89,0.0,17.75,0.0,0,1,42.0,119.0,119.0,151.0,335.0,119.0,142.0,173.0,183.0,17.0,31,10,25.3,0.269,0.1,17.0,2022,1.0,17.823056,1,11.614708,-0.339264,0.500466,1.651551,1.830549,133.66190
3519,3461.0,123.0,1.0,15.0,345.0,1.97,0.0,17.75,0.0,0,1,42.0,366.0,366.0,364.0,382.0,366.0,121.0,142.0,173.0,17.0,31,10,25.3,0.269,0.1,24.0,2022,1.0,17.863333,1,9.320002,-0.223510,0.601590,6.899061,7.340376,348.68440

In [4]:
dwelltime_pred

,trip_id,deviceid,direction,bus_stop,day_of_week,time_of_day,Sunday/holiday,saturday,weekday/end,week_no,dt(w-1),dt(w-2),dt(w-3),dt(t-1),dt(t-2),dt(n-1),dt(n-2),dt(n-3),day,month,temp,precip,windspeed,conditions,rt(n-1),stop_type,dwell_time_in_seconds,year,arrival_hour,arrival_min,arrival_sec,dayparts,starting_speed,ending_speed,average_speed,starting_acceleration,ending_acceleration,average_acceleration,time_to_slow_down,time_to_speed_up,time_stay_stop,predicted_dwell_time,combined_datetime
0,10472.0,505,1,101,0,7.00,0,0,1,34,50.0,50.0,50.0,50.0,50.0,50.0,50.0,50.0,5,9,19.9,0.000,4.7,2,163.0,2,15.0,2022,7,3,30,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.403310,2022-09-05 07:03:30
1,10472.0,505,1,102,0,7.00,0,0,1,34,58.0,58.0,58.0,58.0,58.0,15.0,58.0,58.0,5,9,19.9,0.000,4.7,2,267.0,1,63.0,2022,7,8,12,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.980713,2022-09-05 07:08:12
2,3222.0,123,1,101,0,7.00,0,0,1,34,50.0,50.0,50.0,50.0,50.0,50.0,50.0,50.0,5,9,19.9,0.000,4.7,2,92.0,2,15.0,2022,7,12,41,1,9.053526,5.063021,4.366350,0.121580,0.232660,-0.251850,15.566210,63.687215,23.294521,41.573650,2022-09-05 07:12:41
3,3222.0,123,1,102,0,7.25,0,0,1,34,37.0,45.0,45.0,45.0,45.0,15.0,45.0,45.0,5,9,19.9,0.000,4.7,2,272.0,1,15.0,2022,7,17,28,1,8.827497,10.422770,7.803779,-0.029234,0.343318,-0.049632,22.649203,19.567198,16.938497,36.187170,2022-09-05 07:17:28
4,10472.0,505,1,103,0,7.25,0,0,1,34,23.0,23.0,23.0,23.0,23.0,63.0,15.0,23.0,5,9,19.9,0.000,4.7,2,726.0,1,39.0,2022,7,21,21,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,67.835790,2022-09-05 07:21:21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9328,7560.0,274,1,110,4,17.75,0,0,1,37,20.0,20.0,20.0,0.0,20.0,15.0,15.0,0.0,30,9,23.6,0.719,5.5,4,165.0,1,15.0,2022,17,59,8,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.155418,2022-09-30 17:59:08
9329,7560.0,274,1,111,4,18.00,0,0,1,37,11.0,11.0,13.0,11.0,15.0,15.0,15.0,15.0,30,9,23.0,0.000,11.2,2,154.0,0,15.0,2022,18,1,57,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.493650,2022-09-30 18:01:57
9330,7560.0,274,1,112,4,18.00,0,0,1,37,9.0,9.0,0.0,9.0,9.0,15.0,15.0,15.0,30,9,23.0,0.000,11.2,2,166.0,0,6.0,2022,18,4,58,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.803244,2022-09-30 18:04:58
9331,7560.0,274,1,113,4,18.00,0,0,1,37,12.0,12.0,12.0,12.0,12.0,6.0,15.0,15.0,30,9,23.0,0.000,11.2,2,158.0,1,15.0,2022,18,7,42,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.933297,2022-09-30 18:07:42
9332,7560.0,274,1,114,4,18.00,0,0,1,37,14.0,14.0,14.0,14.0,14.0,15.0,6.0,15.0,30,9,23.0,0.000,11.2,2,115.0,0,15.0,2022,18,9,52,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.613226,2022-09-30 18:09:52

In [5]:
# GET bus stop locations where direction = Kandy-Digana
bustop_locations_kandy_digana = bustop_locations[bustop_locations['direction'] == 'Kandy-Digana']

In [6]:
bustop_locations_kandy_digana

,stop_id,route_id,direction,address,latitude,longitude
0,BT01,654,Kandy-Digana,Kandy,7.292462,80.634978
1,101,654,Kandy-Digana,Wales Park,7.291186,80.637662
2,102,654,Kandy-Digana,Mahamaya,7.287840,80.645840
3,103,654,Kandy-Digana,Lewella junction,7.294430,80.650030
4,104,654,Kandy-Digana,Talwatta,7.286701,80.660336
5,105,654,Kandy-Digana,Tennekumbura Bridge,7.281866,80.666030
6,106,654,Kandy-Digana,Kalapura Junction Busstop,7.279830,80.676210
7,107,654,Kandy-Digana,Nattarampotha Junction Bus Stop,7.279117,80.679450
8,108,654,Kandy-Digana,Kundasale New town,7.280900,80.684160
9,109,654,Kandy-Digana,Warapitiya,7.281490,80.686350
10,110,654,Kandy-Digana,Pallekele (Provincial Council),7.281322,80.696760
11,111,654,Kandy-Digana,Pachchakaatuwa,7.284730,80.705390
12,112,654,Kandy-Digana,Balagolla,7.287349,80.714005
13,113,654,Kandy-Digana,BOI,7.284110,80.722100
14,114,654,Kandy-Digana,Kengalla,7.291520,80.721330
15,BT02,654,Kandy-Digana,Digana,7.298960,80.734720

In [7]:
# concert  runtime_pred['segment'] to integer
runtime_pred['segment'] = runtime_pred['segment'].astype(int)
runtime_pred['trip_id'] = runtime_pred['trip_id'].astype(int)

In [8]:

bus_stops = ['BT01', '101', '102', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112', '113', '114', 'BT02']

# Sort the dataframe by 'trip_id' and 'segment' to ensure correct order
runtime_pred.sort_values(by=['trip_id', 'segment'], inplace=True)

# Calculate 'from_bus_stop' and 'to_bus_stop' based on 'segment'
runtime_pred['from_bus_stop'] = runtime_pred['segment'].apply(lambda x: bus_stops[x - 1] if x != 1 else bus_stops[0])
runtime_pred['to_bus_stop'] = runtime_pred['segment'].apply(lambda x: bus_stops[x] if x != len(bus_stops) - 1 else bus_stops[-1])

runtime_pred

,trip_id,deviceid,direction,segment,run_time_in_seconds,length,day_of_week,time_of_day,Sunday/holiday,saturday,weekday/end,week_no,rt(w-1),rt(w-2),rt(w-3),rt(t-1),rt(t-2),rt(n-1),rt(n-2),rt(n-3),hour_of_day,day,month,temp,precip,windspeed,dt(n-1),year,conditions_encoded,start_float,dayparts,speed,acceleration,radial_acceleration,throttle_count,break_count,predicted_run_time,from_bus_stop,to_bus_stop
120,889,116.0,1.0,1,150.0,0.63,1.0,8.00,0.0,0,1,39.0,111.0,97.0,150.0,97.0,111.0,111.0,111.0,111.0,8.0,11,10,25.3,0.0,0.0,0.0,2022,4.0,8.017222,1,5.953903,-0.030084,0.255768,1.672249,1.428230,115.249850,BT01,101
121,889,116.0,1.0,2,238.0,1.28,1.0,8.00,0.0,0,1,39.0,232.0,293.0,232.0,224.0,232.0,150.0,232.0,232.0,8.0,11,10,25.3,0.0,0.0,60.0,2022,4.0,8.075556,1,7.581270,0.016824,0.523249,3.732057,2.002392,209.659870,101,102
122,889,116.0,1.0,3,336.0,2.11,1.0,8.00,0.0,0,1,39.0,401.0,372.0,401.0,401.0,401.0,238.0,150.0,401.0,8.0,11,10,25.3,0.0,0.0,15.0,2022,4.0,8.145833,1,8.271525,-0.008424,0.534463,8.580336,6.973621,397.526600,102,103
123,889,116.0,1.0,4,158.0,1.55,1.0,8.00,0.0,0,1,39.0,188.0,214.0,188.0,165.0,188.0,336.0,238.0,150.0,8.0,11,10,25.3,0.0,0.0,15.0,2022,4.0,8.243333,1,12.186795,-0.011279,0.414852,4.341404,4.295400,183.983120,103,104
124,889,116.0,1.0,5,124.0,0.84,1.0,8.25,0.0,0,1,39.0,117.0,115.0,164.0,102.0,117.0,158.0,336.0,238.0,8.0,11,10,25.3,0.0,0.0,0.0,2022,4.0,8.287222,1,10.640212,-0.139886,0.278487,2.479419,2.576271,123.188446,104,105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3500,5905,262.0,1.0,11,137.0,1.10,0.0,16.50,0.0,0,1,42.0,120.0,183.0,129.0,116.0,141.0,146.0,20.0,70.0,16.0,31,10,25.1,0.0,5.4,15.0,2022,4.0,16.653889,1,11.210698,-0.371275,0.486406,2.568282,3.202643,151.798140,110,111
3501,5905,262.0,1.0,12,164.0,1.31,0.0,16.50,0.0,0,1,42.0,127.0,177.0,160.0,150.0,177.0,137.0,146.0,20.0,16.0,31,10,25.1,0.0,5.4,3.0,2022,4.0,16.692778,1,11.816637,-0.322288,0.724299,2.875556,3.440000,137.413270,111,112
3502,5905,262.0,1.0,13,129.0,1.15,0.0,16.50,0.0,0,1,42.0,134.0,170.0,150.0,118.0,153.0,164.0,137.0,146.0,16.0,31,10,25.1,0.0,5.4,5.0,2022,4.0,16.739722,1,11.226712,-0.522830,0.651793,2.383592,2.858093,136.122220,112,113
3503,5905,262.0,1.0,14,335.0,0.89,0.0,16.75,0.0,0,1,42.0,184.0,184.0,95.0,184.0,111.0,129.0,164.0,137.0,16.0,31,10,25.1,0.0,5.4,46.0,2022,4.0,16.788333,1,11.499665,-0.320594,0.523476,1.578022,1.865934,132.779070,113,114
3504,5905,262.0,1.0,15,382.0,1.97,0.0,16.75,0.0,0,1,42.0,360.0,360.0,295.0,360.0,317.0,335.0,129.0,164.0,16.0,31,10,25.1,0.0,5.4,15.0,2022,4.0,16.885556,1,9.627592,-0.215678,0.623685,6.734066,7.221978,341.558350,114,BT02

In [9]:
# rename the bus_stop column in dwelltime_pred to from_bus_stop
dwelltime_pred.rename(columns={'bus_stop': 'from_bus_stop'}, inplace=True)

In [10]:
# import pandas as pd

# # Assuming you have two dataframes: dwelltime_pred and runtime_pred
# # dwelltime_pred has columns: 'trip_id', 'bus_stop_id', 'dwell_time_predicted'
# # runtime_pred has columns: 'trip_id', 'segment_id', 'running_time_predicted'

# # Get the order of bus stops
# bus_stop_order = [
#     'BT01', '101', '102', '103', '104', '105', '106', '107', '108', '109', '110',
#     '111', '112', '113', '114', 'BT02'
# ]

# # Merge the two dataframes based on 'trip_id' and 'segment_id'
# merged_df = pd.merge(dwelltime_pred, runtime_pred, on=['trip_id', 'segment'])

# # Calculate the 'from_bus_stop' and 'to_bus_stop' columns
# merged_df['from_bus_stop'] = merged_df['segment'].apply(lambda x: bus_stop_order[x - 1])
# merged_df['to_bus_stop'] = merged_df['segment'].apply(lambda x: bus_stop_order[x])

# # Sort the merged dataframe by 'trip_id' and 'segment_id' to ensure correct order
# merged_df.sort_values(by=['trip_id', 'segment_id'], inplace=True)

# # Calculate the complete_predicted_time column
# merged_df['complete_predicted_time'] = merged_df.groupby('trip_id').apply(
#     lambda group: group['dwell_time_predicted'].shift(1) + group['running_time_predicted']
# ).reset_index(level=0, drop=True)

# # Drop unnecessary columns
# final_df = merged_df.drop(['segment'], axis=1)

# print(final_df)

In [11]:
dwelltime_pred

,trip_id,deviceid,direction,from_bus_stop,day_of_week,time_of_day,Sunday/holiday,saturday,weekday/end,week_no,dt(w-1),dt(w-2),dt(w-3),dt(t-1),dt(t-2),dt(n-1),dt(n-2),dt(n-3),day,month,temp,precip,windspeed,conditions,rt(n-1),stop_type,dwell_time_in_seconds,year,arrival_hour,arrival_min,arrival_sec,dayparts,starting_speed,ending_speed,average_speed,starting_acceleration,ending_acceleration,average_acceleration,time_to_slow_down,time_to_speed_up,time_stay_stop,predicted_dwell_time,combined_datetime
0,10472.0,505,1,101,0,7.00,0,0,1,34,50.0,50.0,50.0,50.0,50.0,50.0,50.0,50.0,5,9,19.9,0.000,4.7,2,163.0,2,15.0,2022,7,3,30,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.403310,2022-09-05 07:03:30
1,10472.0,505,1,102,0,7.00,0,0,1,34,58.0,58.0,58.0,58.0,58.0,15.0,58.0,58.0,5,9,19.9,0.000,4.7,2,267.0,1,63.0,2022,7,8,12,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.980713,2022-09-05 07:08:12
2,3222.0,123,1,101,0,7.00,0,0,1,34,50.0,50.0,50.0,50.0,50.0,50.0,50.0,50.0,5,9,19.9,0.000,4.7,2,92.0,2,15.0,2022,7,12,41,1,9.053526,5.063021,4.366350,0.121580,0.232660,-0.251850,15.566210,63.687215,23.294521,41.573650,2022-09-05 07:12:41
3,3222.0,123,1,102,0,7.25,0,0,1,34,37.0,45.0,45.0,45.0,45.0,15.0,45.0,45.0,5,9,19.9,0.000,4.7,2,272.0,1,15.0,2022,7,17,28,1,8.827497,10.422770,7.803779,-0.029234,0.343318,-0.049632,22.649203,19.567198,16.938497,36.187170,2022-09-05 07:17:28
4,10472.0,505,1,103,0,7.25,0,0,1,34,23.0,23.0,23.0,23.0,23.0,63.0,15.0,23.0,5,9,19.9,0.000,4.7,2,726.0,1,39.0,2022,7,21,21,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,67.835790,2022-09-05 07:21:21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9328,7560.0,274,1,110,4,17.75,0,0,1,37,20.0,20.0,20.0,0.0,20.0,15.0,15.0,0.0,30,9,23.6,0.719,5.5,4,165.0,1,15.0,2022,17,59,8,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.155418,2022-09-30 17:59:08
9329,7560.0,274,1,111,4,18.00,0,0,1,37,11.0,11.0,13.0,11.0,15.0,15.0,15.0,15.0,30,9,23.0,0.000,11.2,2,154.0,0,15.0,2022,18,1,57,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.493650,2022-09-30 18:01:57
9330,7560.0,274,1,112,4,18.00,0,0,1,37,9.0,9.0,0.0,9.0,9.0,15.0,15.0,15.0,30,9,23.0,0.000,11.2,2,166.0,0,6.0,2022,18,4,58,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.803244,2022-09-30 18:04:58
9331,7560.0,274,1,113,4,18.00,0,0,1,37,12.0,12.0,12.0,12.0,12.0,6.0,15.0,15.0,30,9,23.0,0.000,11.2,2,158.0,1,15.0,2022,18,7,42,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.933297,2022-09-30 18:07:42
9332,7560.0,274,1,114,4,18.00,0,0,1,37,14.0,14.0,14.0,14.0,14.0,15.0,6.0,15.0,30,9,23.0,0.000,11.2,2,115.0,0,15.0,2022,18,9,52,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.613226,2022-09-30 18:09:52

In [12]:
import pandas as pd

# Assuming you have two dataframes: dwelltime_pred and runtime_pred
# dwelltime_pred has columns: 'trip_id', 'bus_stop', 'predicted_dwell_time'
# runtime_pred has columns: 'trip_id', 'segment', 'predicted_run_time'

# Convert 'from_bus_stop' column to string data type
dwelltime_pred['from_bus_stop'] = dwelltime_pred['from_bus_stop'].astype(str)
runtime_pred['from_bus_stop'] = runtime_pred['from_bus_stop'].astype(str)

# Merge the two dataframes based on 'trip_id' and 'from_bus_stop' columns
final_df = pd.merge(dwelltime_pred, runtime_pred, on=['trip_id', 'from_bus_stop'], how='right')

In [13]:
final_df

,trip_id,deviceid_x,direction_x,from_bus_stop,day_of_week_x,time_of_day_x,Sunday/holiday_x,saturday_x,weekday/end_x,week_no_x,dt(w-1),dt(w-2),dt(w-3),dt(t-1),dt(t-2),dt(n-1)_x,dt(n-2),dt(n-3),day_x,month_x,temp_x,precip_x,windspeed_x,conditions,rt(n-1)_x,stop_type,dwell_time_in_seconds,year_x,arrival_hour,arrival_min,arrival_sec,dayparts_x,starting_speed,ending_speed,average_speed,starting_acceleration,ending_acceleration,average_acceleration,time_to_slow_down,time_to_speed_up,time_stay_stop,predicted_dwell_time,combined_datetime,deviceid_y,direction_y,segment,run_time_in_seconds,length,day_of_week_y,time_of_day_y,Sunday/holiday_y,saturday_y,weekday/end_y,week_no_y,rt(w-1),rt(w-2),rt(w-3),rt(t-1),rt(t-2),rt(n-1)_y,rt(n-2),rt(n-3),hour_of_day,day_y,month_y,temp_y,precip_y,windspeed_y,dt(n-1)_y,year_y,conditions_encoded,start_float,dayparts_y,speed,acceleration,radial_acceleration,throttle_count,break_count,predicted_run_time,to_bus_stop
0,889,NaN,NaN,BT01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116.0,1.0,1,150.0,0.63,1.0,8.00,0.0,0,1,39.0,111.0,97.0,150.0,97.0,111.0,111.0,111.0,111.0,8.0,11,10,25.3,0.0,0.0,0.0,2022,4.0,8.017222,1,5.953903,-0.030084,0.255768,1.672249,1.428230,115.249850,101
1,889,NaN,NaN,101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116.0,1.0,2,238.0,1.28,1.0,8.00,0.0,0,1,39.0,232.0,293.0,232.0,224.0,232.0,150.0,232.0,232.0,8.0,11,10,25.3,0.0,0.0,60.0,2022,4.0,8.075556,1,7.581270,0.016824,0.523249,3.732057,2.002392,209.659870,102
2,889,NaN,NaN,102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116.0,1.0,3,336.0,2.11,1.0,8.00,0.0,0,1,39.0,401.0,372.0,401.0,401.0,401.0,238.0,150.0,401.0,8.0,11,10,25.3,0.0,0.0,15.0,2022,4.0,8.145833,1,8.271525,-0.008424,0.534463,8.580336,6.973621,397.526600,103
3,889,NaN,NaN,103,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116.0,1.0,4,158.0,1.55,1.0,8.00,0.0,0,1,39.0,188.0,214.0,188.0,165.0,188.0,336.0,238.0,150.0,8.0,11,10,25.3,0.0,0.0,15.0,2022,4.0,8.243333,1,12.186795,-0.011279,0.414852,4.341404,4.295400,183.983120,104
4,889,NaN,NaN,104,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116.0,1.0,5,124.0,0.84,1.0,8.25,0.0,0,1,39.0,117.0,115.0,164.0,102.0,117.0,158.0,336.0,238.0,8.0,11,10,25.3,0.0,0.0,0.0,2022,4.0,8.287222,1,10.640212,-0.139886,0.278487,2.479419,2.576271,123.188446,105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3515,5905,NaN,NaN,110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,262.0,1.0,11,137.0,1.10,0.0,16.50,0.0,0,1,42.0,120.0,183.0,129.0,116.0,141.0,146.0,20.0,70.0,16.0,31,10,25.1,0.0,5.4,15.0,2022,4.0,16.653889,1,11.210698,-0.371275,0.486406,2.568282,3.202643,151.798140,111
3516,5905,NaN,NaN,111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,262.0,1.0,12,164.0,1.31,0.0,16.50,0.0,0,1,42.0,127.0,177.0,160.0,150.0,177.0,137.0,146.0,20.0,16.0,31,10,25.1,0.0,5.4,3.0,2022,4.0,16.692778,1,11.816637,-0.322288,0.724299,2.875556,3.440000,137.413270,112
3517,5905,NaN,NaN,112,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,262.0,1.0,13,129.0,1.15,0.0,16.50,0.0,0,1,42.0,134.0,170.0,150.0,118.0,153.0,164.0,137.0,146.0,16.0,31,10,25.1,0.0,5.4,5.0,2022,4.0,16.739722,1,11.226712,-0.522830,0.651793,2.383592,2.858093,136.122220,113
3518,5905,NaN,NaN,113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,262.0,1.0,14,335.0,0.89,0.0,16.75,0.0,0,1,42.0,184.0,184.0,95.0,184.0,111.0,129.0,164.0,137.0,16.0,31,10,25.1,0.0,5.4,46.0,2022,4.0,16.788333,1,11.499665,-0.320594,0.523476,1.578022,1.865934,132.779070,114
3519,5905,NaN,NaN,114,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,262.0,1.0,15,382.0,1.97,0.0,16.75,0.0,0,1,42.0,360.0,360.0,295.0,360.0,317.0,335.0,129.0,164.0,16.0,31,10,25.1,0.0,5.4,15.0,2022,4.0,16.885556,1,9.627592,-0.215678,0.623685,6.734066,7.221978,341.558350,BT02

In [14]:
# fill nan in predicted_dwell_time with 0
final_df['predicted_dwell_time'].fillna(0, inplace=True)

In [15]:
final_df['total_time'] = final_df['predicted_dwell_time'] + final_df['predicted_run_time']

In [16]:
total_time_df=final_df[['trip_id','deviceid_x','deviceid_y','from_bus_stop','to_bus_stop','predicted_dwell_time','predicted_run_time','total_time']]

In [17]:
# # total_time_df drop nan
# total_time_df.dropna(inplace=True)

In [18]:
bustop_locations_kandy_digana

,stop_id,route_id,direction,address,latitude,longitude
0,BT01,654,Kandy-Digana,Kandy,7.292462,80.634978
1,101,654,Kandy-Digana,Wales Park,7.291186,80.637662
2,102,654,Kandy-Digana,Mahamaya,7.287840,80.645840
3,103,654,Kandy-Digana,Lewella junction,7.294430,80.650030
4,104,654,Kandy-Digana,Talwatta,7.286701,80.660336
5,105,654,Kandy-Digana,Tennekumbura Bridge,7.281866,80.666030
6,106,654,Kandy-Digana,Kalapura Junction Busstop,7.279830,80.676210
7,107,654,Kandy-Digana,Nattarampotha Junction Bus Stop,7.279117,80.679450
8,108,654,Kandy-Digana,Kundasale New town,7.280900,80.684160
9,109,654,Kandy-Digana,Warapitiya,7.281490,80.686350
10,110,654,Kandy-Digana,Pallekele (Provincial Council),7.281322,80.696760
11,111,654,Kandy-Digana,Pachchakaatuwa,7.284730,80.705390
12,112,654,Kandy-Digana,Balagolla,7.287349,80.714005
13,113,654,Kandy-Digana,BOI,7.284110,80.722100
14,114,654,Kandy-Digana,Kengalla,7.291520,80.721330
15,BT02,654,Kandy-Digana,Digana,7.298960,80.734720

In [19]:
total_time_df = pd.merge(total_time_df, bustop_locations_kandy_digana, how='left', left_on='from_bus_stop', right_on='stop_id')

In [20]:
total_time_df

,trip_id,deviceid_x,deviceid_y,from_bus_stop,to_bus_stop,predicted_dwell_time,predicted_run_time,total_time,stop_id,route_id,direction,address,latitude,longitude
0,889,NaN,116.0,BT01,101,0.0,115.249850,115.249850,BT01,654,Kandy-Digana,Kandy,7.292462,80.634978
1,889,NaN,116.0,101,102,0.0,209.659870,209.659870,101,654,Kandy-Digana,Wales Park,7.291186,80.637662
2,889,NaN,116.0,102,103,0.0,397.526600,397.526600,102,654,Kandy-Digana,Mahamaya,7.287840,80.645840
3,889,NaN,116.0,103,104,0.0,183.983120,183.983120,103,654,Kandy-Digana,Lewella junction,7.294430,80.650030
4,889,NaN,116.0,104,105,0.0,123.188446,123.188446,104,654,Kandy-Digana,Talwatta,7.286701,80.660336
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3515,5905,NaN,262.0,110,111,0.0,151.798140,151.798140,110,654,Kandy-Digana,Pallekele (Provincial Council),7.281322,80.696760
3516,5905,NaN,262.0,111,112,0.0,137.413270,137.413270,111,654,Kandy-Digana,Pachchakaatuwa,7.284730,80.705390
3517,5905,NaN,262.0,112,113,0.0,136.122220,136.122220,112,654,Kandy-Digana,Balagolla,7.287349,80.714005
3518,5905,NaN,262.0,113,114,0.0,132.779070,132.779070,113,654,Kandy-Digana,BOI,7.284110,80.722100
3519,5905,NaN,262.0,114,BT02,0.0,341.558350,341.558350,114,654,Kandy-Digana,Kengalla,7.291520,80.721330

In [21]:
# save to csv
total_time_df.to_csv('../DataOut/total_time.csv', index=False)

In [22]:
# total_time is in seconds , convert in to minutes in panas date time
total_time_df['total_time'] = pd.to_datetime(total_time_df['total_time'], unit='s').dt.strftime("%H:%M:%S")

In [23]:
# get all the uniqe trip id s
dwelltime_pred['trip_id'].unique()

array([10472.,  3222.,  7869., 12017.,  7454., 14187.,  4725., 10474.,
        3224.,  7871., 12019.,  8807.,  7456., 14189.,  4727., 10476.,
        3226.,  7873., 12021.,  5684.,  1414., 10478., 13316.,  4728.,
       10976.,  2152.,   747., 14192.,  5686., 10480.,  1416.,  4730.,
       10978.,  2154.,   749., 14194.,  5688., 13320.,  4732., 10980.,
        5690., 12401.,  3228.,  7875., 13322.,  2159.,   753.,  7460.,
       14197.,  6403.,  5692.,  3230.,  7877., 12403., 13324., 10982.,
        2161.,  7462., 14199.,   755.,  5694.,  7879., 12405.,  3232.,
       13326.,  7881.,  2164.,  8809.,  7466.,   757., 12023., 10484.,
       12407.,  3234., 13328.,  1419.,  8811.,   759.,  7468., 12025.,
       10486.,  7883.,  3236.,  7470., 12027., 10488.,   761.,  1421.,
        5696., 10490., 13330.,  7885., 10986.,  2167.,  8813.,   763.,
        7472.,  4734.,  3238., 12029.,  1423.,  5698., 10492., 13332.,
        7887., 10988.,  2169.,  8815.,   765.,  7474.,  4736.,  3240.,
       12031.,  5700., 10494., 10496., 10992.,  8817.,  7476.,  4738.,
        3242.,  7891., 10498., 10994.,  8819.,  7478.,  3244., 10500.,
        1425.,  5701., 12409., 10996.,   767.,  1427.,  5703., 10504.,
       13334., 10998.,  2173.,   769.,  5705., 12033., 11000.,  2175.,
        8822.,   771.,  7480.,  6405., 13336.,  5707., 12035., 11002.,
        2177.,  8824.,   773.,  7482., 13338.,  5709., 12037., 11004.,
        2179.,  8826.,  3247.,   775.,  7484.,  1429.,  5711., 10506.,
        7894.,  2181.,  8828.,   777.,  7486.,  4744.,  3249., 13340.,
       12039.,  1431.,  5713., 10508.,  7896.,  2183.,  8830.,   779.,
        7488.,  4746.,  3251., 13342., 12041.,  5715., 10510.,  7898.,
        2185.,  8832.,  5717., 12410., 10512., 11006.,  7900.,  2187.,
        8834.,   783.,  7492., 14202.,  4750.,  6407.,  3253., 13344.,
       12043.,  5719., 12412., 10514., 11008.,  2189.,  7902.,  8836.,
         785.,  7494., 14204.,  4752.,  6409.,  3255., 13346., 12045.,
        5721., 11010.,  2191.,  7496., 14206.,  4754.,  3257., 10516.,
        1433., 11012.,  7904.,  8840.,  7498., 14208.,  4756.,  3259.,
       12049.,  1435., 10518.,  7906.,  8842.,  7500., 14210.,  4758.,
        3261., 12051.,  7908.,  1437., 10520.,  7502., 14212.,  4760.,
        3263., 12053., 11016.,  1439.,  5723., 12413., 10524., 11018.,
        2193., 14214.,  4762., 13348.,  1441.,  5725., 12415., 10526.,
       11020.,  2195., 14216.,  4764., 13350.,  1443.,  5727., 12417.,
       10528., 11022.,  2197., 14218.,  4766.,  5729.,  5730., 12419.,
       11026.,  8846.,  7910.,   787.,  7504., 14220.,  3265., 13352.,
       12055.,  2199.,  5732., 12421., 11028.,  8848.,  7912.,   789.,
        7506., 14222.,  3267., 13354., 12057.,  2201.,  5734., 11030.,
        7914.,  7508.,  8850.,  1445.,  5736.,   791.,  7916.,  8852.,
        3269., 13356., 12059.,  2203., 10530.,  1447.,  5738.,  7918.,
        8854.,  3271., 13358., 12061.,  2205., 10532.,  5740.,  7920.,
        8856.,  5742., 12423., 10534.,  2209.,   793.,  7510.,  4768.,
        3275., 13362.,  8858., 11032.,  7922.,  5744., 12425., 10536.,
        2211.,   795.,  7512.,  4770.,  3277., 13364.,  8860., 11034.,
        7924., 12427., 10538.,  2213.,   797.,  7514.,  1449., 10540.,
        8864.,  7516.,  7926., 14226.,  4774.,  3281.,  6411., 11036.,
        1451.,  7928., 10542.,  8866.,  7518., 14228.,  4776.,  3283.,
        6413., 11038.,  7930.,  1453., 10544.,  8868.,  7520., 14230.,
        4778.,  3285.,  6415., 11040.,  1455.,  5746., 12429., 10546.,
         799., 14232.,  6417., 13368., 11042.,  2216.,  1457.,  5748.,
       10548.,   801., 12431., 14234.,  6419., 13370., 11044.,  2218.,
        1459.,  5750., 12433., 10550.,   803., 14236.,  6421., 13372.,
        5752.,  8872.,  7522., 14238.,  3287., 13374.,  2220.,   805.,
        5754.,  8874.,  7524., 14240.,  3289., 13376., 11048.,  2222.,
         807.,  5756.,  8876.,  7526., 14242.,  3291., 13378.,  2224.,
        1461.,  5758., 12436.,  7932.,  4780.,  3293., 13380.,  2226.,
        8878.,   811.,  7530.,  1463.,  5760., 12438.,  7934.,  4782.,
        3295.,  8880.,  7936.,   813.,  7532.,  5762., 12440.,  4784.,
        3297., 12442., 10552., 14245.,  4786.,  3299., 13384., 11051.,
        2228.,  8884.,   817.,  7536.,  6425., 12063., 12444., 10554.,
       14247.,  4788.,  3301., 13386., 11053.,  2230.,  8886.,   819.,
        7538.,  6427., 12065., 12446., 10556., 14249.,  3303., 13388.,
       10558.,  7938.,  3305., 11057.,  8890., 12067., 10560.,  7940.,
        3307.,  6429., 11059.,  8892., 12069., 10562.,  7942.,  3309.,
        6431.,  1465.,  5764., 12448., 10564., 14251.,  4790.,  6433.,
       13390., 11063.,  2232.,   821.,  1467.,  5766., 12450., 10566.,
       14253.,  4792.,  6435., 13392., 11065.,  2234.,   823.,  1469.,
        5768., 12452., 10568., 14255.,  4794., 13394.,  2236.,  5770.,
       12454.,   827.,  6437.,  7944.,  3313., 13396., 12071.,  2239.,
        8894.,  7540., 14257.,  5772., 12456.,   829.,  6439.,  3315.,
       13398., 12073., 11067.,  2241.,  7542.,  7946., 12458., 14259.,
        5774.,   831.,  3317., 13400., 12075., 11069., 12460.,  1471.,
        5776., 10570.,  4796.,  7948.,  3319., 12077., 13402.,  2246.,
        8898.,   833.,  7546., 12462.,  7950.,  1473.,  5778., 10572.,
        4798.,  3321., 12079., 13404.,  2248.,  7952.,  8900.,   835.,
        7548.,  5780.,  3323., 12081., 10574.,  5782., 10576.,  4800.,
        6441.,  7954.,  3325., 13406., 11071.,  2250.,  8904.,   837.,
        7550., 14262., 12465.,  1476.,  5784., 10578.,  4802.,  6443.,
        3327., 13408., 11073.,  8906.,   839.,  7956.,  7552., 14264.,
        1478.,  5786., 10580.,  4804.,  3329.,  6445., 13410.,  6447.,
        3331.,  7958., 12085., 11077.,  8910.,  7556., 10582.,  1481.,
        6449.,  3333., 12087., 11079.,  8912.,  7558., 10584.,  7960.,
        1483.,  6451.,  3335., 12089., 11081.,  8914.,  7560.])

In [24]:
runtime_pred['trip_id'].unique()

array([ 889,  891,  893,  897,  899,  901,  903,  905,  907,  909,  911,
        913,  915,  917,  919,  921,  925,  927,  929,  931,  933,  935,
        937,  939,  941,  943,  945,  947,  949,  951,  953,  957,  959,
        961,  963, 1511, 1513, 1515, 1517, 1519, 1521, 1523, 1525, 1527,
       1529, 1531, 1533, 1535, 1537, 1539, 1541, 1543, 1545, 1547, 1549,
       1551, 1553, 1555, 1557, 1559, 1561, 2283, 2285, 2287, 2289, 2291,
       2293, 2295, 2297, 2299, 2301, 2303, 2305, 2308, 2310, 2312, 2315,
       2317, 2319, 2322, 2324, 2326, 2329, 2331, 2333, 2335, 2337, 2341,
       2343, 2347, 2349, 2353, 2355, 2359, 2361, 2364, 2366, 2368, 3371,
       3373, 3375, 3377, 3379, 3381, 3383, 3385, 3387, 3389, 3391, 3397,
       3399, 3401, 3403, 3405, 3407, 3409, 3411, 3413, 3415, 3417, 3419,
       3421, 3423, 3425, 3429, 3431, 3433, 3435, 3437, 3439, 3441, 3443,
       3445, 3447, 3449, 3451, 3453, 3455, 3459, 3461, 4196, 4198, 4202,
       4204, 4206, 4208, 4210, 4212, 4214, 4216, 4218, 4220, 4222, 4224,
       4228, 4230, 4232, 4234, 4236, 4238, 4240, 4242, 4244, 4246, 4832,
       4834, 4836, 4838, 4840, 4842, 4844, 4846, 4848, 4850, 4852, 4854,
       4856, 4858, 4860, 4862, 4864, 4868, 4870, 4872, 4874, 4876, 4878,
       4880, 4882, 4884, 4886, 4888, 5818, 5820, 5822, 5824, 5826, 5828,
       5830, 5832, 5834, 5836, 5838, 5840, 5842, 5844, 5846, 5848, 5850,
       5852, 5854, 5856, 5858, 5860, 5862, 5864, 5866, 5868, 5870, 5872,
       5874, 5876, 5878, 5880, 5882, 5884, 5886, 5888, 5890, 5892, 5894,
       5896, 5898, 5899, 5901, 5903, 5905])